springdoc:
  swagger-ui:
    enabled: false
  api-docs:
    enabled: false

elasticsearch:
  index-name: ocean-current-files-prod
  indexing:
    cron:
      expression: 0 30 1/2 * * ? # every 2 hours starting at 1:30 AM in Australia/Hobart time

logging:
  level:
    au.org.aodn.oceancurrent: info
