springdoc:
  swagger-ui:
    enabled: false
  api-docs:
    enabled: false

elasticsearch:
  index-name: ocean-current-files-prod
  indexing:
    cron:
      expression: 0 0 3/4 * * ? # every 4 hours starting at 3 AM in Australia/Hobart time

logging:
  level:
    au.org.aodn.oceancurrent: info
